[tox]
minversion = 3.20
envlist = py39
skipsdist = true

[testenv]
basepython = python3.9
deps =
    ansible-core==2.15.13
    molecule==6.0.3
    molecule-plugins[podman]==23.5.0
passenv =
    ANSIBLE_*
    DOCKER_*
    PODMAN_*
    HOME
    USER
whitelist_externals =
    molecule
commands =
    molecule test -s podman
