input {
  beats { port => 5046 }
  tcp {
    port => 5044
    codec => json_lines
    tags => ["tcp-json"]
  }
}
filter {
  if [container][name] == "monitoring-04-dummy-1" and [message] =~ /^\s*\{/ {
    json {
      source => "message"
      target => "app"
      skip_on_invalid_json => true
    }
  }
  if "tcp-json" in [tags] {
    mutate { add_field => { "[@metadata][index]" => "tcp-json" } }
  } else {
    mutate { add_field => { "[@metadata][index]" => "logstash" } }
  }
}
output {
  elasticsearch {
    hosts => ["http://es-hot:9200"]
    index => "%{[@metadata][index]}-%{+yyyy.MM.dd}"
    ilm_enabled => false
    data_stream => false
    manage_template => true
    template_name => "netology-logs"
    template => "/usr/share/logstash/config/logstash-template.json"
    template_overwrite => true
  }
}
