---
galaxy_info:
  author: demon-5656
  description: Install Vector from archive
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies: []
