---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: community.docker.docker

vector:
  hosts:
    vector-01:
      ansible_connection: community.docker.docker

lighthouse:
  hosts:
    lighthouse-01:
      ansible_connection: community.docker.docker
