---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: vector-ubuntu
    image: ubuntu:latest
    command: sleep infinity
    pre_build_image: true
  - name: vector-oraclelinux
    image: oraclelinux:8
    command: sleep infinity
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
  inventory:
    host_vars:
      vector-oraclelinux:
        ansible_python_interpreter: /usr/bin/python3.9
  config_options:
    defaults:
      interpreter_python: auto_silent
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
