---
- name: Test installed collection from archive
  hosts: localhost
  gather_facts: false
  roles:
    - role: demon5656.yandex_cloud_elk.write_text_file
      vars:
        text_file_path: /tmp/netology_installed_collection.txt
        text_file_content: "Installed collection works"
        text_file_mode: "0644"
